replicaCount: 1

image:
  repository: "<remote-repository-url>"
  tag: "<tag>"
  pullPolicy: "Always"
  initContainer:
    repository: "<remote-repository-url>"
    tag: "<tag>"
    pullPolicy: "Always"

config:
  namespace: "my-namespace"
  serviceAccount: "my-service-account-name"

  mountFolder: "/some/directory/path"
  logPath: "/some/log-directory/path"
  configPath: "/some/config-directory/path"
  secretsPath: "/some/directory/path"

  environment: production
  hostname: production-hostname
  domain: production

dbConfig:
  dbUrl: jdbc:mysql://production.host:3306/mydb
  dbUsername: production-user
  
# Service level configuration pointing towards the local port of container(s) inside Pod(s).
service:
  type: ClusterIP | NodePort
  port: 8080
