apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: "{{ .Values.config.namespace }}"
  labels:
    app: my-springboot-helloworld-app
    chart: my-chart
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  common.properties: |
    jetty.http.port={{ .Values.service.port }}
    jetty.threads.max=512
    jetty.threads.min=64
    jetty.queued.max=1
  application.properties: |
    spring.datasource.url={{ .Values.dbConfig.dbUrl }}
    spring.datasource.username={{ .Values.dbConfig.dbUsername }}
