apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: "{{ .Values.config.namespace }}"
  labels:
    app: my-springboot-helloworld-app
    chart: my-chart
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: mainport
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: my-springboot-helloworld-app
  type: {{ .Values.service.type }}
