apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: "{{ .Values.config.namespace }}"
  labels:
    app: my-app
    chart: my-chart
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # Using pipeline, chaining several functions together
  game.properties: |
    my.favourite.sport={{ .Values.favourite.sport | quote }}
    my.favourite.club={{ .Values.favourite.club | upper | quote }}
    my.favourite.location={{ .Values.favourite.location | default "London, UK" | quote }}
    my.favourite.slogan={{ .Values.favourite.slogan | repeat 3 | quote }}
