apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: "{{ .Values.config.namespace }}"
  labels:
    app: my-app
    chart: my-chart
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # Using pipeline, chaining several functions together
  # default: specify a default value inside of the template, in case the value is omitted in values.yaml file
  # quote: will add quotation marks to the given string value
  # repeat: will echo the given string the given number of times
  # upper: will transform the given string into UPPER_CASE
  game.properties: |
    my.favourite.sport={{ .Values.favourite.sport | quote }}
    my.favourite.club={{ .Values.favourite.club | upper | quote }}
    my.favourite.location={{ .Values.favourite.location | default "London, UK" | quote }}
    my.favourite.slogan={{ .Values.favourite.slogan | repeat 3 | quote }}
