---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: "{{ .Values.config.namespace }}"
  labels:
    app: my-app
    chart: my-chart
    # Release is one of the top-level objects that you can access in your templates.
    # Release object contains several objects like:
    # Release.Name: The release name
    # Release.Service: The service that is rendering the present template. On Helm, this is always Helm.
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: my-app
        chart: my-chart
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      # Values passed into the template from the values.yaml file and/or from user-supplied files.
      # By default, Values is empty.
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        # Chart.Name: The chart name
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
