apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: "{{ .Values.config.namespace }}"
  labels:
    app: my-app
    chart: my-chart
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ingressClassName: my-ingress-class-name
  # Ingress backed by a single service with default backend and no rules.
  defaultBackend:
    service:
      name: {{ .Values.service.name }}
      port:
        number: {{ .Values.service.port }}
