apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: "{{ .Values.config.namespace }}"
  labels:
    app: my-app
    chart: my-chart
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  game.properties: |
    my.favourite.sport=Football
    my.favourite.club=Chelsea
