apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: "{{ .Values.config.namespace }}"
  labels:
    app: my-app
    chart: my-chart
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
# The data field is used to store arbitrary data, encoded using base64.
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm